[global]
developmentMode = false

[server]
port = 8501
address = "127.0.0.1"
headless = false

[client]
toolbarMode = "minimal"
#showSidebarNavigation = true  # ページナビゲーション非表示

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[ui]
hideTopBar = false  # トップバーは表示（ユーザビリティのため）
