[global]
developmentMode = false

[server]
port = 8501
address = "0.0.0.0"  # Render.com対応
headless = true  # 非インタラクティブモード
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "minimal"
#showSidebarNavigation = true  # ページナビゲーション非表示

[browser]
gatherUsageStats = false
# serverAddress設定を削除（Render.comで自動設定）

[ui]
hideTopBar = false  # トップバーは表示（ユーザビリティのため）

# Render.com用の追加設定
[logger]
level = "info"
