[global]
developmentMode = false

[server]
port = 8501
address = "0.0.0.0"
headless = true

[client]
toolbarMode = "minimal"
#showSidebarNavigation = true  # ページナビゲーション非表示

[browser]
gatherUsageStats = false

[ui]
hideTopBar = false  # トップバーは表示（ユーザビリティのため）