[global]
# 開発モードを無効にしてページナビゲーションを非表示
developmentMode = false

[server]
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false